export default {

    ZONES_RECEIVED: 'ZONES_RECEIVED',
    ZONE_CREATED: 'ZONE_CREATED',
    SELECTED_ZONE: 'SELECT_ZONE',

    COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
    COMMENT_CREATED: 'COMMENT_CREATED',

    ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    ACCOUNT_LOGIN: 'ACCOUNT_LOGIN',
    ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT'

}