export default {

    ZONES_RECEIVED: 'ZONES_RECEIVED',
    ZONE_CREATED: 'ZONE_CREATED',
    SELECTED_ZONE: 'SELECT_ZONE',

    COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
    COMMENT_CREATED: 'COMMENT_CREATED',
    COMMENT_UPDATED: 'COMMENT_UPDATED',

    CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',

    PROFILE_RECEIVED: 'PROFILE_RECEIVED',
    APPLICATION_STATE: 'APPLICATION_STATE',
    PROFILE_UPDATED: 'PROFILE_UPDATED'

}